### ISSUE TITLE
Merge Source and Sink data types

### ISSUE THREAD

**Issue by felipenoris** [JuliaDB/DataStreams.jl#10]
I noticed that `Table` is used by CSV as a Sink.
On DataStreams you had to define the following:
```julia
# define our own default Data.stream! method since Data.Table <: Source
function Data.stream!(source::Data.Source, ::Type{Data.Table})
```
On the tests I wrote, `TableSink` was supposed to be defined also inside the package.
But maybe a better design is to merge Source and Sink, since a previous Sink can become a new Source.

**Comment by quinnj** [comment]
While technically possible, in many packages, it's conceptually clearer to separate out Sources from Sinks. Usually there is some sort of "setup" or "tear down" that happens during Source/Sink construction which is different between the types.
