### ISSUE TITLE
Data.Table is not defined

### ISSUE THREAD

**Issue by ararslan** [JuliaDB/DataStreams.jl#12]
It looks like `Data.Table` is no longer being defined, which seems to be what's causing the test failures on master. Based on a conversation I read elsewhere (can't seem to find it at the moment), I guess it's being replaced by `DataFrame`? If that's the case, the tests should probably be modified, or at least commented out for now.

**Comment by quinnj** [comment]
You got it. Fixed tests in 2db401c792a56dca51486ed398a465becc959f68
