### ISSUE TITLE
interface stability

### ISSUE THREAD

**Issue by tbreloff** [JuliaDB/DataStreams.jl#2]
I'm very excited about DataStreams becoming a standard interface for streaming data... thanks for doing it. Is the interface stable at this point, or could the core design/naming change?

**Comment by quinnj** [comment]
I would say it's in a fairly solid beta stage. Meaning, I've already ported 2.5 packages over to using the interface as is and made most of the changes necessary. Obviously on the roadmap is reaching out to various "DataStream" candidate packages and helping to spread the framework, which will help things evolve over time, but in terms of the core set of functionality, I've tried to keep things pretty minimal upfront.

**Comment by tbreloff** [comment]
Cool thanks.  You can count on Plots, OnlineStats, and OnlineAI being
candidates for the interface...

**Comment by tpoisot** [comment]
And is there a documentation somwhere? I'm trying to wrap my head around how to convert from DataStreams to the DataFrames package, for example.

**Comment by quinnj** [comment]
@tpoisot, to convert to a DataFrame, just do
```julia
DataFrame(dt::Data.Table)
```
it converts without copying. I'll add some docs around this.
