### ISSUE TITLE
Data.Table

### ISSUE THREAD

**Issue by mwsohn** [JuliaDB/DataStreams.jl#5]
The example shown in the DataStreams.jl blog does not work. What is Data.Table in

# stream our data into a Julia structure (Data.Table)
dt = Data.stream!(sqlite_source, Data.Table)

**Comment by Dawny33** [comment]
Can you add a link to the blog post please?

[This](https://github.com/JuliaDB/DataStreams.jl/blob/master/src/DataStreams.jl#L130-L133) might help you understand it better.

**Comment by mwsohn** [comment]
Here it is: http://julialang.org/blog/2015/10/datastreams

**Comment by quinnj** [comment]
Let me know if you're still having issues, but everything should be working.
